import 'package:powersync/powersync.dart';

const Schema schema = Schema([
  Table('products', [
    Column.text('tenant_id'),
    Column.text('name'),
    Column.text('description'),
    Column.text('sku'),
    Column.text('barcode'),
    Column.text('category_id'),
    Column.real('cost_price'),
    Column.real('selling_price'),
    Column.integer('current_stock'),
    Column.integer('track_inventory'), // stored as 0 or 1
    Column.text('expiry_date'),
    Column.text('image_url'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('sales', [
    Column.text('tenant_id'),
    Column.text('sale_number'),
    Column.text('customer_id'),
    Column.text('cashier_id'),
    Column.real('total_amount'),
    Column.text('payment_method'),
    Column.text('status'),
    Column.text('created_at'),
  ]),
  Table('sale_items', [
    Column.text('tenant_id'),
    Column.text('sale_id'),
    Column.text('product_id'),
    Column.text('product_name'),
    Column.integer('quantity'),
    Column.real('unit_price'),
    Column.real('total_price'),
  ]),
  Table('inventory_transactions', [
    Column.text('tenant_id'),
    Column.text('branch_id'),
    Column.text('product_id'),
    Column.text('transaction_type'),
    Column.integer('quantity_delta'),
    Column.integer('previous_quantity'),
    Column.integer('new_quantity'),
    Column.real('unit_cost'),
    Column.text('reference_id'),
    Column.text('reference_type'),
    Column.text('notes'),
    Column.text('staff_id'),
    Column.text('created_at'),
  ]),
  Table('customers', [
    Column.text('tenant_id'),
    Column.text('full_name'),
    Column.text('phone_number'),
    Column.text('email'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('orders', [
    Column.text('tenant_id'),
    Column.text('branch_id'),
    Column.text('order_number'),
    Column.text('customer_id'),
    Column.text('order_status'),
    Column.text('payment_status'),
    Column.real('subtotal'),
    Column.real('total_amount'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('order_items', [
    Column.text('tenant_id'),
    Column.text('order_id'),
    Column.text('product_id'),
    Column.text('product_name'),
    Column.integer('quantity'),
    Column.real('unit_price'),
    Column.real('subtotal'),
  ]),
  Table('deliveries', [
    Column.text('tenant_id'),
    Column.text('order_id'),
    Column.text('driver_name'),
    Column.text('driver_phone'),
    Column.text(
      'delivery_status',
    ), // pending, picked_up, in_transit, delivered, failed
    Column.text('delivery_address'),
    Column.real('delivery_fee'),
    Column.text('notes'),
    Column.text('estimated_delivery_time'),
    Column.text('actual_delivery_time'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
]);
